version: '3.8'
services:
  frontend:
    image: node:18.20
    container_name: pfip_angular_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install && npm start"

  backend:
    image: node:18.20
    container_name: pfip_nestjs_app
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/tasksdb
    command: >
      sh -c "npm install && npm run start:dev"

  db:
    image: postgres:13
    container_name: pfip_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: